"""full schema

Revision ID: 001_initial
Revises: 
Create Date: 2026-03-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###

    # Таблица пользователей
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('GUEST', 'CLIENT', 'TECHNICIAN', 'MANAGER', 'ADMIN', name='userrole'), nullable=False, server_default='CLIENT'),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), nullable=False, server_default='0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Таблица клиентов
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('total_orders', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('loyalty_tier', sa.String(), nullable=False, server_default='bronze'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])

    # Таблица техников
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('completed_orders', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('portfolio_description', sa.String(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False, server_default='true'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_technicians_id'), 'technicians', ['id'], unique=False)
    op.create_foreign_key(None, 'technicians', 'users', ['user_id'], ['id'])

    # Категории услуг
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=True)

    # Услуги
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_foreign_key(None, 'services', 'service_categories', ['category_id'], ['id'])

    # Материалы
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False, server_default='0.0'),
    sa.Column('min_quantity', sa.Numeric(), nullable=False, server_default='0.0'),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)

    # Заказы
    op.create_table('orders',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='orderstatus'), nullable=False, server_default='NEW'),
    sa.Column('priority', sa.Enum('NORMAL', 'URGENT', 'CRITICAL', name='orderpriority'), nullable=False, server_default='NORMAL'),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.0'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'technicians', ['technician_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['manager_id'], ['id'])

    # Позиции заказа
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'services', ['service_id'], ['id'])

    # Файлы заказов
    op.create_table('order_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('uploaded_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_files_id'), 'order_files', ['id'], unique=False)
    op.create_foreign_key(None, 'order_files', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_files', 'users', ['uploaded_by'], ['id'])

    # История статусов заказа
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('changed_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('old_status', sa.Enum('NEW', 'CONFIRMED', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='orderstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('NEW', 'CONFIRMED', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='orderstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_status_history', 'users', ['changed_by'], ['id'])

    # Запросы материалов
    op.create_table('material_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ISSUED', name='materialrequeststatus'), nullable=False, server_default='PENDING'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requests_id'), 'material_requests', ['id'], unique=False)
    op.create_foreign_key(None, 'material_requests', 'technicians', ['technician_id'], ['id'])
    op.create_foreign_key(None, 'material_requests', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'material_requests', 'users', ['resolved_by'], ['id'])

    # Отзывы
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_moderated', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('is_published', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'orders', ['order_id'], ['id'])

    # Статьи
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])

    # Акции
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('applies_to', sa.Enum('ALL', 'SERVICE', 'CATEGORY', name='promotionappliesto'), nullable=False, server_default='ALL'),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)

    # База знаний
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_foreign_key(None, 'knowledge_base', 'users', ['created_by'], ['id'])

    # Логи действий
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_id'), 'action_logs', ['id'], unique=False)
    op.create_foreign_key(None, 'action_logs', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table('action_logs')
    op.drop_table('knowledge_base')
    op.drop_table('promotions')
    op.drop_table('articles')
    op.drop_table('reviews')
    op.drop_table('material_requests')
    op.drop_table('order_status_history')
    op.drop_table('order_files')
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('materials')
    op.drop_table('services')
    op.drop_table('service_categories')
    op.drop_table('technicians')
    op.drop_table('clients')
    op.drop_table('users')
    # ### end Alembic commands ###
