"""
Схемы Pydantic для приложения.
"""
from .service import (
    ServiceCategoryBase,
    ServiceCategoryCreate,
    ServiceCategoryUpdate,
    ServiceCategoryResponse,
    ServiceBase,
    ServiceCreate,
    ServiceUpdate,
    ServiceResponse,
    ServiceListResponse,
)
from .order import (
    OrderStatusEnum,
    OrderPriorityEnum,
    OrderItemBase,
    OrderItemCreate,
    OrderItemResponse,
    OrderFileResponse,
    OrderStatusHistoryResponse,
    OrderBase,
    OrderCreate,
    OrderUpdate,
    OrderStatusUpdate,
    OrderAssignRequest,
    OrderResponse,
    OrderListResponse,
    OrderSummaryResponse,
)
from .calculator import (
    CalculatorItem,
    CalculatorRequest,
    CalculatedItem,
    PromotionInfo,
    CalculatorResponse,
)
from .clients import (
    ClientSummary,
    ClientOrderSummary,
    ClientDetailResponse,
    ClientListResponse,
    ClientLoyaltyUpdate,
    TechnicianSummary,
    TechnicianDetailResponse,
    TechnicianStatsResponse,
    TechnicianPortfolioResponse,
    TechnicianUpdate,
)
from .materials import (
    MaterialBase,
    MaterialCreate,
    MaterialUpdate,
    MaterialResponse,
    MaterialListResponse,
    MaterialRequestStatusEnum,
    MaterialRequestCreate,
    MaterialRequestUpdate,
    MaterialRequestResponse,
    MaterialRequestListResponse,
)
from .secondary import (
    # Reviews
    ReviewCreate,
    ReviewResponse,
    ReviewListResponse,
    ReviewModerateRequest,
    # Articles
    ArticleCreate,
    ArticleUpdate,
    ArticleResponse,
    ArticleListResponse,
    # Promotions
    PromotionCreate,
    PromotionUpdate,
    PromotionResponse,
    PromotionListResponse,
    # Knowledge Base
    KnowledgeBaseCreate,
    KnowledgeBaseUpdate,
    KnowledgeBaseResponse,
    KnowledgeBaseListResponse,
    # Analytics
    OrderAnalyticsResponse,
    RevenueAnalyticsResponse,
    RevenueByPeriod,
    RevenueByCategory,
    TechnicianAnalyticsResponse,
    TechnicianAnalyticsItem,
    # Admin
    ActionLogResponse,
    ActionLogListResponse,
    UserSummaryResponse,
    UserListResponse,
    UserRoleUpdate,
    UserStatusUpdate,
    BackupResponse,
)

__all__ = [
    # Service
    "ServiceCategoryBase",
    "ServiceCategoryCreate",
    "ServiceCategoryUpdate",
    "ServiceCategoryResponse",
    "ServiceBase",
    "ServiceCreate",
    "ServiceUpdate",
    "ServiceResponse",
    "ServiceListResponse",
    # Order
    "OrderStatusEnum",
    "OrderPriorityEnum",
    "OrderItemBase",
    "OrderItemCreate",
    "OrderItemResponse",
    "OrderFileResponse",
    "OrderStatusHistoryResponse",
    "OrderBase",
    "OrderCreate",
    "OrderUpdate",
    "OrderStatusUpdate",
    "OrderAssignRequest",
    "OrderResponse",
    "OrderListResponse",
    "OrderSummaryResponse",
    # Calculator
    "CalculatorItem",
    "CalculatorRequest",
    "CalculatedItem",
    "PromotionInfo",
    "CalculatorResponse",
    # Clients
    "ClientSummary",
    "ClientOrderSummary",
    "ClientDetailResponse",
    "ClientListResponse",
    "ClientLoyaltyUpdate",
    # Technicians
    "TechnicianSummary",
    "TechnicianDetailResponse",
    "TechnicianStatsResponse",
    "TechnicianPortfolioResponse",
    "TechnicianUpdate",
    # Materials
    "MaterialBase",
    "MaterialCreate",
    "MaterialUpdate",
    "MaterialResponse",
    "MaterialListResponse",
    "MaterialRequestStatusEnum",
    "MaterialRequestCreate",
    "MaterialRequestUpdate",
    "MaterialRequestResponse",
    "MaterialRequestListResponse",
    # Secondary
    "ReviewCreate",
    "ReviewResponse",
    "ReviewListResponse",
    "ReviewModerateRequest",
    "ArticleCreate",
    "ArticleUpdate",
    "ArticleResponse",
    "ArticleListResponse",
    "PromotionCreate",
    "PromotionUpdate",
    "PromotionResponse",
    "PromotionListResponse",
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseResponse",
    "KnowledgeBaseListResponse",
    "OrderAnalyticsResponse",
    "RevenueAnalyticsResponse",
    "RevenueByPeriod",
    "RevenueByCategory",
    "TechnicianAnalyticsResponse",
    "TechnicianAnalyticsItem",
    "ActionLogResponse",
    "ActionLogListResponse",
    "UserSummaryResponse",
    "UserListResponse",
    "UserRoleUpdate",
    "UserStatusUpdate",
    "BackupResponse",
]
